// Code generated by protoc-gen-gogo.
// source: internal/data.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal/data.proto

It has these top-level messages:
	WriteShardRequest
	WriteShardResponse
	ExecuteStatementRequest
	ExecuteStatementResponse
	CreateIteratorRequest
	CreateIteratorResponse
	FieldDimensionsRequest
	FieldDimensionsResponse
*/
package internal

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WriteShardRequest struct {
	ShardID          *uint64  `protobuf:"varint,1,req,name=ShardID" json:"ShardID,omitempty"`
	Points           [][]byte `protobuf:"bytes,2,rep,name=Points" json:"Points,omitempty"`
	Database         *string  `protobuf:"bytes,3,opt,name=Database" json:"Database,omitempty"`
	RetentionPolicy  *string  `protobuf:"bytes,4,opt,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *WriteShardRequest) Reset()         { *m = WriteShardRequest{} }
func (m *WriteShardRequest) String() string { return proto.CompactTextString(m) }
func (*WriteShardRequest) ProtoMessage()    {}

func (m *WriteShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *WriteShardRequest) GetPoints() [][]byte {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *WriteShardRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *WriteShardRequest) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

type WriteShardResponse struct {
	Code             *int32  `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WriteShardResponse) Reset()         { *m = WriteShardResponse{} }
func (m *WriteShardResponse) String() string { return proto.CompactTextString(m) }
func (*WriteShardResponse) ProtoMessage()    {}

func (m *WriteShardResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *WriteShardResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ExecuteStatementRequest struct {
	Statement        *string `protobuf:"bytes,1,req,name=Statement" json:"Statement,omitempty"`
	Database         *string `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExecuteStatementRequest) Reset()         { *m = ExecuteStatementRequest{} }
func (m *ExecuteStatementRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteStatementRequest) ProtoMessage()    {}

func (m *ExecuteStatementRequest) GetStatement() string {
	if m != nil && m.Statement != nil {
		return *m.Statement
	}
	return ""
}

func (m *ExecuteStatementRequest) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

type ExecuteStatementResponse struct {
	Code             *int32  `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExecuteStatementResponse) Reset()         { *m = ExecuteStatementResponse{} }
func (m *ExecuteStatementResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteStatementResponse) ProtoMessage()    {}

func (m *ExecuteStatementResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *ExecuteStatementResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type CreateIteratorRequest struct {
	ShardIDs         []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Opt              []byte   `protobuf:"bytes,2,req,name=Opt" json:"Opt,omitempty"`
	Database         []byte   `protobuf:"bytes,3,req,name=Database" json:"Database,omitempty"`
	RetentionPolicy  []byte   `protobuf:"bytes,4,req,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	MeasurementName  []byte   `protobuf:"bytes,5,req,name=MeasurementName" json:"MeasurementName,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CreateIteratorRequest) Reset()         { *m = CreateIteratorRequest{} }
func (m *CreateIteratorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIteratorRequest) ProtoMessage()    {}

func (m *CreateIteratorRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *CreateIteratorRequest) GetOpt() []byte {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *CreateIteratorRequest) GetDatabase() []byte {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *CreateIteratorRequest) GetRetentionPolicy() []byte {
	if m != nil {
		return m.RetentionPolicy
	}
	return nil
}

func (m *CreateIteratorRequest) GetMeasurementName() []byte {
	if m != nil {
		return m.MeasurementName
	}
	return nil
}

type CreateIteratorResponse struct {
	Err              *string `protobuf:"bytes,1,opt,name=Err" json:"Err,omitempty"`
	DataType         *int32  `protobuf:"varint,2,opt,name=DataType" json:"DataType,omitempty"`
	SeriesN          *int32  `protobuf:"varint,3,opt,name=SeriesN" json:"SeriesN,omitempty"`
	PointN           *int32  `protobuf:"varint,4,opt,name=PointN" json:"PointN,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateIteratorResponse) Reset()         { *m = CreateIteratorResponse{} }
func (m *CreateIteratorResponse) String() string { return proto.CompactTextString(m) }
func (*CreateIteratorResponse) ProtoMessage()    {}

func (m *CreateIteratorResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func (m *CreateIteratorResponse) GetDataType() int32 {
	if m != nil && m.DataType != nil {
		return *m.DataType
	}
	return 0
}

func (m *CreateIteratorResponse) GetSeriesN() int32 {
	if m != nil && m.SeriesN != nil {
		return *m.SeriesN
	}
	return 0
}

func (m *CreateIteratorResponse) GetPointN() int32 {
	if m != nil && m.PointN != nil {
		return *m.PointN
	}
	return 0
}

type FieldDimensionsRequest struct {
	ShardIDs         []uint64 `protobuf:"varint,1,rep,name=ShardIDs" json:"ShardIDs,omitempty"`
	Measurement      []byte   `protobuf:"bytes,2,req,name=Sources" json:"Sources,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FieldDimensionsRequest) Reset()         { *m = FieldDimensionsRequest{} }
func (m *FieldDimensionsRequest) String() string { return proto.CompactTextString(m) }
func (*FieldDimensionsRequest) ProtoMessage()    {}

func (m *FieldDimensionsRequest) GetShardIDs() []uint64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *FieldDimensionsRequest) GetMeasurement() []byte {
	if m != nil {
		return m.Measurement
	}
	return nil
}

type FieldDimensionsResponse struct {
	Fields           []byte   `protobuf:"bytes,1,rep,name=Fields" json:"Fields,omitempty"`
	Dimensions       []string `protobuf:"bytes,2,rep,name=Dimensions" json:"Dimensions,omitempty"`
	Err              *string  `protobuf:"bytes,3,opt,name=Err" json:"Err,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FieldDimensionsResponse) Reset()         { *m = FieldDimensionsResponse{} }
func (m *FieldDimensionsResponse) String() string { return proto.CompactTextString(m) }
func (*FieldDimensionsResponse) ProtoMessage()    {}

func (m *FieldDimensionsResponse) GetFields() []byte {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *FieldDimensionsResponse) GetDimensions() []string {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func (m *FieldDimensionsResponse) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*WriteShardRequest)(nil), "internal.WriteShardRequest")
	proto.RegisterType((*WriteShardResponse)(nil), "internal.WriteShardResponse")
	proto.RegisterType((*ExecuteStatementRequest)(nil), "internal.ExecuteStatementRequest")
	proto.RegisterType((*ExecuteStatementResponse)(nil), "internal.ExecuteStatementResponse")
	proto.RegisterType((*CreateIteratorRequest)(nil), "internal.CreateIteratorRequest")
	proto.RegisterType((*CreateIteratorResponse)(nil), "internal.CreateIteratorResponse")
	proto.RegisterType((*FieldDimensionsRequest)(nil), "internal.FieldDimensionsRequest")
	proto.RegisterType((*FieldDimensionsResponse)(nil), "internal.FieldDimensionsResponse")
}
